apiVersion: batch/v1
kind: Job
metadata:
  name: astra-manage-app
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    spec:
      volumes:
        - name: astra-control-config
          secret:
            secretName: astra-control-config
      containers:
      - name: alpine-actoolkit
        image: alpine:latest
        env:
          - name: APPNAME
            value: "ghost-argocd"
          - name: NAMESPACE
            value: "ghost"
          - name: LABEL
            value: "volume=persistent"
          - name: ACTOOLKIT_VERSION
            value: "2.6.2"
        command: ["/bin/sh"]
        args:
        - -c
        - >
          apk add py3-pip jq &&
          python3 -m pip install --upgrade pip &&
          python3 -m pip install actoolkit==$ACTOOLKIT_VERSION &&
          for i in `actoolkit -o json list namespaces -m 30 -f $NAMESPACE | jq -r '.items[].clusterID'`;
          do
            app_exists=$(actoolkit -o json list apps -f $APPNAME -n $NAMESPACE -c $i | jq  -r '.items[].id' | wc -l) &&
            if [ ${app_exists} -gt 0 ] ; then
              echo $APPNAME already exists, nothing to do;
            else
              echo actoolkit: managing app $APPNAME in namespace $NAMESPACE on cluster $i;
              actoolkit manage app $APPNAME $NAMESPACE $i -l $LABEL;
              sleep 5;
              for j in `actoolkit -o json list apps -f $APPNAME | jq -r '.items[].id'`;
              do
                echo actoolkit: creating protection policy for $APPNAME / $j;
                actoolkit create protection $j -g hourly  -m 0      -b 1 -s 1;
                actoolkit create protection $j -g daily   -H 0      -b 2 -s 2;
                actoolkit create protection $j -g weekly  -H 0 -W 1 -b 2 -s 2;
                actoolkit create protection $j -g monthly -H 0 -M 1 -b 2 -s 2;
              done
            fi
          done
        volumeMounts:
          - mountPath: /etc/astra-toolkits
            name: astra-control-config
            readOnly: true
      restartPolicy: Never
  backoffLimit: 1
